### ISSUE TITLE
little Roadmap to 0.1.0

### ISSUE THREAD

**Issue by Andre-LA** [Andre-LA/rotor-quick#2]
# New features (on order of priority, but not strictly)
---
- [x] Scene Graph Node
- [x] Position Hierarchy
---
- [x] Sprite Animation
---
- [x] ~~"Any" Animation (animate variables for example, this is available on engines like Unity and Godot, and are very useful)~~ (it's possible though)
---
- [x] ~~Transform (will replace "position" component, will support scale and rotation)~~ (0.2.0)
- [x] Position Hierarchy (scene graph)
- [x] ~~Transform Hierarchy Painter?~~
---
- [x] ~~Anchored Rect (to make GUIs)~~ (0.2.0)
- [x] ~~Anchored Text~~
- [x] ~~Anchored Sprite~~
- [x] ~~Anchored Rect Hierarchy (scene graph)~~
- [x] ~~Anchored Rect Painter~~

# Refactors
- [x] Refactor `rotor-quick.makers` and update tests
- [x] ~~(external) Refactor and optimize `Rotor`~~ (now unrelated)
- [x] Use Nene `v.2.x`

**Comment by Andre-LA** [comment]
Conditions met to release as `v0.1.0`, however, it will only be officially released after the refactor of [Alpinist game] (https://github.com/Andre-LA/alpinist-vs-the-mount-roraima-alien-invasion).

Other goals will be added as issues

**Comment by Andre-LA** [comment]
This library have been rewritten from scratch privately, the source will be public eventually, but this roadmap doesn't represents the current work on it.
